### PR TITLE
Start active default finish

### PR DESCRIPTION
**Pull request by carlosalberto**
Compatibility with OT' PR: https://github.com/opentracing/opentracing-python/pull/67

### CODE REVIEW

**Comment by palazzem** [comment]
@carlosalberto I see some tests failing in the CI:
```
AttributeError: 'bool' object has no attribute 'context'
```

I think it has not been updated since now the second argument is `child_of` (that's why the error is about a `bool`).

**Comment by carlosalberto** [comment]
Hey!

Oh, it's the fact it's referencing a dependency to the `v2.0.0` branch (which does not have this default value *yet*) :(

**Comment by carlosalberto** [comment]
Confirmed it works against the v2.0.0 branch of `opentracing-python` (made Travis re-run after the latest PR was merged).

Looks ok to merge? @palazzem @yurishkuro

**Comment by carlosalberto** [comment]
Merged prior to do our second RC ;) Let me know if anything needs further adjustments.

**Comment by palazzem** [comment]
@carlosalberto I think that's great!

**Pull request merged**
